Vet clinic database: query and update animals table
rabayarabu/vet_clinic_db pull request #2
Opened 2023-07-19 06:02 UTC by rabayarabu

- Add a column species of type string to your animals table.
- Insert data.
- Inside a transaction update the animals table by setting the species column to unspecified.
- Update the animals table by setting the species column to digimon for all animals that have a name ending in mon.
- Update the animals table by setting the species column to pokemon for all animals that don't have species already set.

#Some analytical questions answers:

1. How many animals are there?
2. How many animals have never tried to escape?
3. What is the average weight of animals?
4. Who escapes the most, neutered or not neutered animals?
5. What is the minimum and maximum weight of each type of animal?
6. What is the average number of escape attempts per animal type of those born between 1990 and 2000?

Here, are screenshots of my actions:

![Screenshot 2023-07-19 113738](https://github.com/rabayarabu/vet_clinic_db/assets/70410637/2e7e9fca-23a5-4d9e-bcfd-683fa8ba5b9e)
![Screenshot 2023-07-19 114537](https://github.com/rabayarabu/vet_clinic_db/assets/70410637/ac22c0bd-d880-4c59-b219-4e38224f615e)
![Screenshot 2023-07-19 114904](https://github.com/rabayarabu/vet_clinic_db/assets/70410637/dd5fd06e-38f2-467b-9502-b7859238c46d)
![Screenshot 2023-07-19 114939](https://github.com/rabayarabu/vet_clinic_db/assets/70410637/202ace9a-8c59-4c9a-8747-6adc8880e84f)
![Screenshot 2023-07-19 115013](https://github.com/rabayarabu/vet_clinic_db/assets/70410637/2ad86a9f-c330-4125-9520-9953632b09a8)
![Screenshot 2023-07-19 115048](https://github.com/rabayarabu/vet_clinic_db/assets/70410637/98a76820-fede-412e-83a0-5c303f98b0e4)
![Screenshot 2023-07-19 115145](https://github.com/rabayarabu/vet_clinic_db/assets/70410637/566e61cd-eb94-40d2-9698-8fa46cd6036e)
![Screenshot 2023-07-19 115225](https://github.com/rabayarabu/vet_clinic_db/assets/70410637/6717f042-261d-43b0-9c04-68d39293f755)
![Screenshot 2023-07-19 115301](https://github.com/rabayarabu/vet_clinic_db/assets/70410637/4355e563-2a48-4e27-9f39-73154842370f)

2023-07-19 06:11 UTC, mikethreels requested changes
Hi Rabu, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Good job altering the table

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-19 06:11 UTC, mikethreels commented on queries.sql
> +COMMIT;
- [ ] according to the requirements you should check if the changes persist after the commit as well.

2023-07-19 06:11 UTC, mikethreels commented on queries.sql
> +ROLLBACK;
- [ ] according to the requirements you should check if the records are deleted before the rollback.

2023-07-19 06:11 UTC, mikethreels commented on queries.sql
> +UPDATE animals SET weight_kg=weight_kg*-1 WHERE weight_kg<0;
- [ ] According to the requirements you're supposed to rollback to the savepoint in between the update transactions

2023-07-20 11:15 UTC, rotimiazeez approved these changes
Hi @rabayarabu 👏🏽, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Good job implementing the required changes 👍🏽
- All query results are accurate 👏🏽
- Descriptive PR title and summary 👌🏽
- Screenshots of results are present in the PR 👍🏼


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me(@rotimiazeez) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-20 11:22 UTC, merged

2023-08-15 11:27 UTC, V-Blaze reviewed
Hi @rabayarabu 

# Approved 🟢 🟢 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![approved-accepted](https://user-images.githubusercontent.com/107632780/229279070-96b4e89d-83fd-4f9f-acc2-649c7cee2957.gif)

## Highlights
- Correct data inserted into the database✔✔
- Queries are written correctly :heavy_check_mark: 
- Screenshots show correct results :heavy_check_mark: 
- Readme looks professional :heavy_check_mark: 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._